### ISSUE TITLE
Cannot create an instance of......because Type.ContainsGenericParameters is true

### ISSUE THREAD

**Issue by vawwyakr** [oleg-shilo/cs-script#134]
I am trying to use the Roslyn compiler but if I use any anonymous objects (eg: "var t = new { test = ""test"" }") I get the below error. Is there a work around for this?  This script compiles with Mono but I have other issues with Mono and would prefer not to have to switch compilers based on script all over the place.  

Error:
Cannot create an instance of <>f__AnonymousType0#1`1[<Envelope>j__TPar] because Type.ContainsGenericParameters is true.

StackTrace:
  at System.RuntimeType.CreateInstanceCheckThis()
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at CSScriptLibraryExtensionMethods.CreateInstance(Assembly assembly, String typeName, Object[] args)
   at CSScriptLibrary.AsmBrowser.createInstance(Assembly asm, String typeName, Object[] args)
   at CSScriptLibrary.AsmBrowser.CreateInstance(String typeName, Object[] args)
   at CSScriptLibraryExtensionMethods.CreateObject(Assembly obj, String typeName, Object[] args)
   at CSScriptLibrary.RoslynEvaluator.LoadCode(String scriptText, Object[] args)

**Comment by oleg-shilo** [comment]
This is a compiler (e.g. Roslyn) specific issue that is unfortunately impossible to address by scripting infrastructure (CS-Script). 

This is not that surprising considering that quite a few normal syntax concepts are illegal in Roslyn scripting implementation. IE _"error CS7021: Cannot declare namespace in script code"_

It also looks like it is something that is under consideration by the Roslyn team: [[Proposal] Allow explicit declaration of anonymous types (in local collections) #3304](https://github.com/dotnet/roslyn/issues/3304)

**Comment by vawwyakr** [comment]
Wow ok darn I was hoping there might be some parameter being passed into the compiler that caused this.  So Roslyn can't do anonymous types, interesting.  Thank you!

**Comment by oleg-shilo** [comment]
> So Roslyn can't do anonymous types, interesting.

I know. Hard to believe, right!
