### ISSUE TITLE
Wrong path when running on Linux

### ISSUE THREAD

**Issue by pietrodicaprio** [oleg-shilo/cs-script#146]
When using ```CSScript.EvaluatorConfig.RefernceDomainAsemblies = true;``` the call ```CSScript.Evaluator.CompileCode(t.Code).CreateObject("*");``` raises an exception due to ```Could not find file '/usr/.../...\Libraries\Custom.DomainLoaded.dll'.``` when the OS is Linux based (currently using CentOS). It works fine when running on Windows.
The issue should be the kind of 'slash': the exception prints a 'backslash \' and this makes the path as invalid/not existent since it should contain only '/'

Anyone had the same issue?

Regards

**Comment by oleg-shilo** [comment]
can you provide the exception stack please?

**Comment by pietrodicaprio** [comment]
here it is

```csharp
2019-02-13 19:22:15 FATAL #°° Foundation.Scripting.TaskEngine.LoadInstanceTasks °°# Exception has been thrown by the target of an invocation. §
2019-02-13 19:22:16 FATAL #°° Foundation.Scripting.TaskEngine.LoadInstanceTasks °°#    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.LazyHelper.CreateViaDefaultConstructor(Type type)
   at System.Lazy`1.CreateViaDefaultConstructor()
   at System.Lazy`1.ViaConstructor()
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at CSScriptLib.CSScript.get_RoslynEvaluator()
   at SubPixel.OwnBusiness.Foundation.Scripting.TaskEngine.LoadInstanceTasks() in C:\Development\Repos\SubPixel\OwnBusiness\ob-foundation\SubPixel.OwnBusiness.Foundation\Scripting\TaskEngine.cs:line 72 §
2019-02-13 19:22:16 FATAL #°° Foundation.Scripting.TaskEngine.LoadInstanceTasks (Inner ex) °°# Could not find file '/usr/share/nginx/apidev.domain.it\Libraries\SubPixel.OwnBusiness.Communication.dll'. §
2019-02-13 19:22:16 FATAL #°° Foundation.Scripting.TaskEngine.LoadInstanceTasks (Inner ex) °°#    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.<>c__DisplayClass4_0`2.<SelectChecked>b__0(T item)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.AddRangeChecked[T](ArrayBuilder`1 builder, IEnumerable`1 items, String parameterName)
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.ConcatChecked[T](ImmutableArray`1 existing, IEnumerable`1 items, String parameterName)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.AddReferences(IEnumerable`1 references)
   at CSScriptLib.RoslynEvaluator.ReferenceAssembly(Assembly assembly)
   at CSScriptLib.RoslynEvaluator.ReferenceDomainAssemblies(DomainAssemblies assemblies)
   at CSScriptLib.RoslynEvaluator..ctor() §
```

**Comment by oleg-shilo** [comment]
It is a very strange error. I do not see any place where Path concatenation happens with hard codded `"\"`.

I am trying to get a Linux virtual image to test it. In a mean time instead of relying on CS-Script assembly probing you can reference the required assembly with the full path instead:
```C#
CSScript.Evaluator
        .ReferenceAssembly(Path.Combine(basePath, "Libraries", "<your assembly>"))             
        .CompileCode(t.Code)
        .CreateObject("*");
```

**Comment by oleg-shilo** [comment]
OK, I have tested it. It seems that the problem does not come from the runtime environment being Linux. The attached sample project runs the same way Linux as on windows:
![image](https://user-images.githubusercontent.com/16729806/52900307-772d4380-3248-11e9-8cc1-e8f751c2e76a.png)
![image](https://user-images.githubusercontent.com/16729806/52900317-91672180-3248-11e9-97d3-56eda9ae457a.png)

```C#
static void Main(string[] args)
{
    CSScript.GlobalSettings.AddSearchDir("lib");

    dynamic script = CSScript.RoslynEvaluator
                                .ReferenceAssembly("utils.dll")
                                .CompileCode(@"using System;
                                            public class Script
                                            {
                                                public int Sum(int a, int b)
                                                {
                                                    Output.WriteLine(""Script.Sum(...)"");
                                                    return a+b;
                                                }
                                            }")
                                .CreateObject("*");

    var result = script.Sum(7, 3);
    Console.WriteLine(result);
}
```   

[Debug.zip](https://github.com/oleg-shilo/cs-script/files/2871938/Debug.zip)
