### ISSUE TITLE
Could not find file exception

### ISSUE THREAD

**Issue by pavelkux** [oleg-shilo/cs-script#246]
Hello.
If this is not the right place for such post, please feel free to delete it straight away. 
I am using CSScript for several years and I find it amazing. Yet, on some machines I get this:
```
Could not find file 'C:\Users\user\AppData\Local\Temp\CSSCRIPT\Cache\-45648060\b0fb795e-4280-40ee-b1e4-bc50a59549b5.tmp.compiled'.
 Stack Trace [   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at System.IO.FileSystemInfo.set_LastWriteTimeUtc(DateTime value)
   at csscript.CSExecutor.ProcessCompilingResult(CompilerResults results, CompilerParameters compilerParams, ScriptParser parser, String scriptFileName, String assemblyFileName, String[] additionalDependencies)
   at csscript.CSExecutor.Compile(String scriptFileName)
   at csscript.CSExecutor.Compile(String scriptFile, String assemblyFile, Boolean debugBuild)
   at CSScriptLibrary.CSScript.LoadWithConfig(String scriptFile, String assemblyFile, Boolean debugBuild, Settings scriptSettings, String compilerOptions, String[] refAssemblies)
   at CSScriptLibrary.CSScript.LoadCode(String scriptText, String tempFileExtension, String assemblyFile, Boolean debugBuild, String[] refAssemblies)
   at CSScriptLibrary.CSScript.LoadCode(String scriptText, String assemblyFile, Boolean debugBuild, String[] refAssemblies)
```
Is there any potential reasons for this? We tried to set permissions for "everyone" full control on that folder CSSCRIPT but it didnt help. 
I am still using 3.13.0.0 version.
Thank you for your help.

**Comment by oleg-shilo** [comment]
Sorry for such a late response and not useful one 😞 
I se no obvious reason for that.

Your attempt to reset permissions it is exactly what I would do. Antivirus locking the file, folder?

Most likely you will fix it by disabling the caching during the execution `cscs -c:0 <your script>` but then.... you have no caching.

**Comment by pavelkux** [comment]
Thank you very much for response. Do not worry about the delay.
I was also thinking about antivirus, but the antivirus is probably out of the question - we advised users to add the exe file to exceptions there.
Just in case - if caching is disabled, what performance impact does it have? Is it just the caching between "sessions" when you exit the app and start again? Or even during one session there is a drawback?

**Comment by oleg-shilo** [comment]
Caching is works globally and it is persistent. Like python caching.
If the script is not changed since the last execution then instead of compiling it the script engine takes the compiled script from the cache. And this brings the performance to the exact level of the compiled .NET application.

if you have caching disabled then the script will be compiled every time user executes it. .NET Framework version is relatively fast anyway but .NET 5/Core compiler is shockingly slow.

you can also try to reconfigure location of the cache directory so it is possibly excluded form some permission policies. You can reconfigure the whole CS-Script temp directory (cache dir is a subfolder there):
```
cscs -config:set=CustomTempDirectory=<new temp dir>
```

**Comment by pavelkux** [comment]
Thank you again for reply.
I have changed the code and added ability to manually set temp folder. I didnt want to lose the caching ability. I didn't find CustomTempDirectory but I guess that it is because I am using older version of the code.
I hope this will solve the issues. 
Thank you for your help and again - Kudos to your work!
