### ISSUE TITLE
.net 5  error for  publish  Single file application

### ISSUE THREAD

**Issue by shshshdy** [oleg-shilo/cs-script#247]
Value cannot be null. (Parameter 'path')   at System.IO.Path.GetFullPath(String path)
   at CSScriptLib.EvaluatorBase`1.<>c.<GetReferencedAssemblies>b__28_1(String x)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at CSScriptLib.EvaluatorBase`1.GetReferencedAssemblies(String code, String[] searchDirs)
   at CSScriptLib.EvaluatorBase`1.ReferenceAssembliesFromCode(String code, String[] searchDirs)
   at CSScriptLib.RoslynEvaluator.Compile(String scriptText, String scriptFile, CompileInfo info)
   at CSScriptLib.EvaluatorBase`1.CompileCode(String scriptText, String scriptFile, CompileInfo info)
   at CSScriptLib.EvaluatorBase`1.CompileCode(String scriptText, CompileInfo info)
   at Server.GetScripts(DirectoryInfo dirInfo)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by oleg-shilo** [comment]
Possible duplication: https://github.com/oleg-shilo/cs-script/issues/245
