### ISSUE TITLE
Exception thrown: 'System.Reflection.TargetInvocationException' in CSScriptLibrary.dll

### ISSUE THREAD

**Issue by watashigoto** [oleg-shilo/cs-script#276]
Hi, I want to build for WPF .NET Framework 4.6, I want to use the Hosted script feature to execute external script in my program.

I used the sample [here](https://github.com/oleg-shilo/cs-script/blob/master/src/CSScriptLib/src/Client.WPF/MainWindow.xaml.cs) but I got this error:

```
Exception thrown: 'System.Reflection.TargetInvocationException' in CSScriptLibrary.dll
error:    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at CSScriptLibrary.CSScript.get_RoslynEvaluator()
   at Tesskrip.MainWindow.Test_Roslyn() in D:\wstudio\Tesskrip\MainWindow.xaml.cs:line 19
```

Code
```
using CSScriptLibrary;
using System;
using System.Windows;

namespace Tesskrip
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            Test_Roslyn();
            InitializeComponent();
        }

        public void Test_Roslyn()
        {
            try
            {
                dynamic script = CSScript.RoslynEvaluator
                     .LoadMethod(@"public int func()
                                    {
                                        return 123;
                                 }");

                dynamic result = script.func();

                Console.WriteLine("result: " + result);
            } catch(Exception e)
            {
                Console.WriteLine("error: " + e.StackTrace);
            }

        }

    }
}


```

packages.config
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="CS-Script.lib" version="3.30.5.1" targetFramework="net46" />
</packages>
```

I installed CS-Script.lib 3.30.5.1 from nuget. 
After I read [this page](https://github.com/oleg-shilo/cs-script.net-framework/releases/tag/split-point), I also tried 3.30.0 but still got the same error.

**Comment by oleg-shilo** [comment]
I have attached the working project sample for you
![image](https://user-images.githubusercontent.com/16729806/151965867-bde62a34-a6b2-4ef7-8236-bb98995474c5.png)
[WpfApp1.zip](https://github.com/oleg-shilo/cs-script/files/7978290/WpfApp1.zip)

Please note that you are using a discontinued release stream targeting .NET Framework that is no longer supported due to the fact that .NET Fraework has been superseded with .NET Core.

**Comment by watashigoto** [comment]
Thank you! It's working now. So I need the CodeAnalyzers as well..

Yes I'm aware that I'm targeting outdated .NET, I appreciate your info :)
