### ISSUE TITLE
Unable to compile script using CodeDom on macos

### ISSUE THREAD

**Issue by int2e** [oleg-shilo/cs-script#370]
code:
```
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;
    CSScript.EvaluatorConfig.DebugBuild = true;
    dynamic script = CSScript.Evaluator
        .With(eval => eval.IsCachingEnabled = false)
        .LoadFile(scriptPath);
    script.Run();
```

error:
```
CSScriptLib.CompilerException: BUILD: error : System.Net.Sockets.SocketException (61): Connection refused [::ffff:127.0.0.1]:17001
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at CSScriptLib.BuildServer.Request(String request, Nullable`1 port)
   at CSScriptLib.BuildServer.SendBuildRequest(String[] args, Nullable`1 port)

   at CSScriptLib.CodeDomEvaluator.CompileAssemblyFromFileBatch_with_Csc(String[] fileNames, String[] ReferencedAssemblies, String outAssembly, Boolean IncludeDebugInformation, CompileInfo info)
   at CSScriptLib.CodeDomEvaluator.Compile(String scriptText, String scriptFile, CompileInfo info)
   at CSScriptLib.EvaluatorBase`1.CompileCode(String scriptText, String scriptFile, CompileInfo info)
   at CSScriptLib.EvaluatorBase`1.LoadFile(String scriptFile, Object[] args)
```

Please confirm whether it is a bug?

**Comment by oleg-shilo** [comment]
I cannot be sure but the error means that CS-Script build server is not active for some reason.
CodeDom engine compiles either directly with C# compiler csc.exe or on the BuildServer, which is nothing else but a high-performing csc.exe runner `build.dll` (part of CS-Script distro). The build server is extracted and deployed on the target system on the first use of CodeDom engine. After the build server is deployed and started the script engine pushes the compiling job to this build pipeline by using a socket channel that is failing in your case.

The possible failure reasons to check: 

1. BuildServer is not deployed successfully. You can check it by checking the value ``CSCSripting.Globals.BuildServerIsDeployed`.
2. BuildServer cannot start. This may happen if csc.exe is not present on the system. Or it is not allowed to open sockets.
    You can check if you can start it from your code:
    ` Process.Start("dotnet", $@"""{Globals.build_server}"" -listen -port:{BuildServer.serverPort} -csc:""{Globals.csc}""");`

If you cannot sort it out for the BuildServer then you can try to do the compilation in the same process that hosts your script engine. Just set `CodeDomEvaluator.CompileOnServer = false;`.

You will still need to have `csc.exe`. Thus if you want to use CodeDom then you need to install .NET SDK.

----------------

All these potential problems would normally be detected and the descriptive exception thrown:

![image](https://github.com/oleg-shilo/cs-script/assets/16729806/8caab812-3d9c-4c8b-999b-b6d226a3f80e)

But for some reason, it's not the case in your environment.

**Comment by oleg-shilo** [comment]
Glad it's all sorted out

**Comment by yao-big** [comment]
@int2e May I ask how to use this cs script on Mac? I couldn't find any information
