### ISSUE TITLE
Error while compiling related to environment block

### ISSUE THREAD

**Issue by zerodevelop** [oleg-shilo/cs-script#47]
Hi Oleg,

I've realized a system that uses several db stored script to respond to events.
At the moment I have thirty different script that can be launched from a windows service.
Recently I'm having issues when the service tries to compile a script.
Once I got the exception on the first script, that can be a random one, all other script compilations fail with the same error.
If I then restart the service, for a while the script won't compile becausa they can't find the host service assemblies that are located in the bin.

I think the problem is related to the environment variabled added by csscript.
Can you give some advice about how to avoid this problem?

The error is:
`System.InvalidOperationException: The environment block used to start a process cannot be longer than 65535 bytes.  Your environment block is 65633 bytes long.  Remove some environment variables and try again.
   at System.Diagnostics.EnvironmentBlock.ToByteArray(StringDictionary sd, Boolean unicode)
   at System.CodeDom.Compiler.Executor.ExecWaitWithCaptureUnimpersonated(SafeUserTokenHandle userToken, String cmd, String currentDir, TempFileCollection tempFiles, String& outputName, String& errorName, String trueCmdLine)
   at System.CodeDom.Compiler.Executor.ExecWaitWithCapture(SafeUserTokenHandle userToken, String cmd, String currentDir, TempFileCollection tempFiles, String& outputName, String& errorName, String trueCmdLine)
   at Microsoft.CSharp.CSharpCodeGenerator.Compile(CompilerParameters options, String compilerDirectory, String compilerExe, String arguments, String& outputFile, Int32& nativeReturnValue, String trueArgs)
   at Microsoft.CSharp.CSharpCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromFileBatch(CompilerParameters options, String[] fileNames)
   at csscript.CSExecutor.CompileAssembly(ICodeCompiler compiler, CompilerParameters compilerParams, String[] filesToCompile)
   at csscript.CSExecutor.Compile(String scriptFileName)
   at csscript.CSExecutor.Compile(String scriptFile, String assemblyFile, Boolean debugBuild)
   at CSScriptLibrary.CSScript.LoadWithConfig(String scriptFile, String assemblyFile, Boolean debugBuild, Settings scriptSettings, String compilerOptions, String[] refAssemblies)
   at CSScriptLibrary.CSScript.LoadCode(String scriptText, String tempFileExtension, String assemblyFile, Boolean debugBuild, String[] refAssemblies)
   at CSScriptLibrary.CodeDomEvaluator.CompileCode(String scriptText)
   at CSScriptLibrary.CodeDomEvaluator.LoadCode[T](String scriptText, Object[] args)`

**Comment by oleg-shilo** [comment]
Indeed the error it related to CS-Script preserving the locations of the original scripts via environment variables. While this being a useful technique it can lead to the situations like yours. This it is a defect. 

You can desable this feature in the very latest release (v3.24.2) via dedicated config variable: 
```C#
CSScript.EnableScriptLocationReflection = false;
```

**Comment by zerodevelop** [comment]
Thank you Oleg!
I'll update my Nuget package and let you know if all work fine.

**Comment by zerodevelop** [comment]
I've been monitoring the service in these days and the issue no longer shows up.
Thank you again.

**Comment by oleg-shilo** [comment]
Cool, thank you for reporting. Without your feedback I would never guess that there is a limit on how many environment variables a process can have. :)
