### ISSUE TITLE
Does this even work?

### ISSUE THREAD

**Issue by Jofairden** [oleg-shilo/cs-script#54]
Hi, I'm trying to use this with np++. I installed using chocolatey and np++ plugin manager.
When trying to compile I'm constantly getting:  https://i.imgur.com/inECidD.png
I have .net 4.6, roselyn is working fine in visual studio

On debugging I get in debug output:
`The system cannot find the file specified`

On debug external process I get:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CSScriptNpp.DebugExternal.<GetProcessList>d__11.MoveNext()
   at CSScriptNpp.DebugExternal.Repopulete(Boolean refetch)
   at CSScriptNpp.DebugExternal.<Reload>b__8_0()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
CSScriptNpp
    Assembly Version: 1.6.3.0
    Win32 Version: 1.6.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Notepad++/plugins/CSScriptNpp.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
CSScriptIntellisense
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Notepad++/plugins/CSScriptNpp/CSScriptIntellisense.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Intellisense.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Notepad++/plugins/CSScriptNpp/Intellisense.Common.DLL
----------------------------------------
ICSharpCode.NRefactory
    Assembly Version: 5.0.0.0
    Win32 Version: 5.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Notepad++/plugins/CSScriptNpp/ICSharpCode.NRefactory.DLL
----------------------------------------
CSScriptLibrary
    Assembly Version: 3.24.0.0
    Win32 Version: 3.24.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Notepad++/plugins/CSScriptNpp/CSScriptLibrary.DLL
----------------------------------------
Mono.Cecil
    Assembly Version: 0.9.5.0
    Win32 Version: 0.9.5.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Notepad++/plugins/CSScriptNpp/Mono.Cecil.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
ICSharpCode.NRefactory.CSharp
    Assembly Version: 5.0.0.0
    Win32 Version: 5.2.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Notepad++/plugins/CSScriptNpp/ICSharpCode.NRefactory.CSharp.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```
Here's my chocolatey power shell install result:
```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> choco install cs-script
Chocolatey v0.10.3
Installing the following packages:
cs-script
By installing you accept licenses for the packages.

cs-script v3.24.0.0 [Approved]
cs-script package files install completed. Performing other installation steps.
The package cs-script wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Downloading cs-script
  from 'https://github.com/oleg-shilo/cs-script/releases/download/v3.24.0/cs-script.7z'
Progress: 100% - Completed download of C:\Users\Admin\AppData\Local\Temp\chocolatey\cs-script\3.24.0.0\cs-script.7z (9.6 MB).
Download of cs-script.7z (9.6 MB) completed.
Extracting C:\Users\Admin\AppData\Local\Temp\chocolatey\cs-script\3.24.0.0\cs-script.7z to C:\ProgramData\chocolatey\lib\cs-script\tools...
C:\ProgramData\chocolatey\lib\cs-script\tools
Cannot find a process with the name "VBCSCompiler". Verify the process name and call the cmdlet again.
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 ShimGen has successfully created a shim for cscs.exe
 ShimGen has successfully created a shim for css.exe
 ShimGen has successfully created a shim for css_config.exe
 ShimGen has successfully created a shim for csws.exe
 ShimGen has successfully created a shim for nuget.exe
 ShimGen has successfully created a shim for ResGen.exe
 ShimGen has successfully created a shim for cscs.exe
 ShimGen has successfully created a shim for cscs.exe
 ShimGen has successfully created a shim for csws.exe
 ShimGen has successfully created a shim for cscs.exe
 ShimGen has successfully created a shim for csws.exe
 ShimGen has successfully created a shim for cscs.exe
 ShimGen has successfully created a shim for cscs32.exe
 ShimGen has successfully created a shim for csws.exe
 ShimGen has successfully created a shim for csws32.exe
 ShimGen has successfully created a shim for csc.exe
 ShimGen has successfully created a shim for csi.exe
 ShimGen has successfully created a shim for vbc.exe
 ShimGen has successfully created a shim for VBCSCompiler.exe
 ShimGen has successfully created a shim for ConfigConsole.exe
 ShimGen has successfully created a shim for ChooseDefaultProgram.exe
 ShimGen has successfully created a shim for CS-Script.exe
 ShimGen has successfully created a shim for App.exe
 The install of cs-script was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\cs-script\tools'

Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\WINDOWS\system32>
```

Running windows 10

**Comment by oleg-shilo** [comment]
>Does this even work?

CS-Script has been downloaded ~950,000 times and ~550,000 times as part of Notepad++ plugin. Thus there is a good chance it works. :)

Anyway, on a serious note, the problem is caused by the incorrectly deployed Notepad++ plugin and it has nothing to do with CS-Script. I will reflect on the problem cause and how to fix it but for the further discussion it's probably better to take it to the **plugin** speific discussion board: http://csscriptnpp.codeplex.com. Thus please log an issue request there.

The problem is caused by the latest update to the Notepad++ and specifically to the _Plugin Manager_. It no longer respects sub-folders in the package file and extracts (merges) all the plugin files in a single directory. Thus files cannot be found, assemblies cannot be resolved. 

Reporting this bug to the Notepad++ team is possible but expecting the fix is unrealistic. Last time it took me ~6 moth. Thus I will need to provide the fix via plugin own update channel. But untill it's done please use remove plugin and install it manually. The instructions are here: https://csscriptnpp.codeplex.com/wikipage?title=Manual%20Installation

**Comment by Jofairden** [comment]
I know it works, I just couldn't figure out a good title.
Manual install worked. I already noticed it was trying to look in subfolders which didn't exist, but the root folder did have all the files. Let's hope it gets fixed.

**Comment by Jofairden** [comment]
Is it correct thought that only the _args_ array shows in my 'locals' tab?

**Comment by oleg-shilo** [comment]
Honestly, I had very painful experience with N++ support. 
Last time my package was screwed I had to chase the Plugin Manager maintainer on his tweeter and yet without any luck. While at the same time I had to answer to my angry users. 

>...shows in my 'locals' tab?

The locals tab content is determined not by plugin but by the CLR debugger (MDbg.exe). Thus if the debugger believes that in the current debug context args is the only available symbol then this is what plugin shows.

For any non "locals" primitive  symbols you can use mouse roll-over with tooltip or "watch" tab.

**Comment by Jofairden** [comment]
I see. Well that's kinda sad. I made a ton of local variables but none showed up, hovering them did work fine though.

**Comment by Jofairden** [comment]
Hmm also on further testing, when trying to look for virtual methods which can be overridden, it finds none: https://cdn.discordapp.com/attachments/103110554649894912/292244321892040704/unknown.png

**Comment by oleg-shilo** [comment]
I have created the issue on your behalf: https://csscriptnpp.codeplex.com/workitem/21#
