### ISSUE TITLE
Issues referencing custom .exe

### ISSUE THREAD

**Issue by Jofairden** [oleg-shilo/cs-script#55]
I'm trying to reference a game .exe and using code from it, but I get the following error:

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at csscript.RemoteExecutor.InvokeStaticMain(Assembly compiledAssembly, String[] scriptArgs)
   at csscript.CSExecutor.ExecuteImpl()

```

Here's my code:
```
//css_args /ac
//css_ref "Terraria.exe"
using Terraria;
using Terraria.ModLoader;
using System;
using System.Diagnostics;
using System.Windows.Forms;

public class Script
{
    [STAThread]
    static public void Main(string[] args)
    {
        Console.WriteLine("Hello World!");
        Debug.WriteLine("Hello World!");
        Console.ReadKey();
    }
}

public class MyMod : Mod
{
    public MyMod()
    {
        Properties = new ModProperties()
        {
            Autoload = true
        };
    }

    public override void Load()
    {
        throw new Exception("Test exception on load");
    }
}
```

It's finding the .exe properly. Removing MyMod class and it works.

**Comment by oleg-shilo** [comment]
It is impossible to know what is the cause of the problem. There will be something in the Terraria.exe. But it looks like there is some dependency problem. 

The attached sample shows the use-case you are inquiring about. 
[Jofairden.zip](https://github.com/oleg-shilo/cs-script/files/852241/Jofairden.zip)

BTW, you don't need to use `//css_args -ac` as your script is not classless.
